import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainComponent from "@/components/MainComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MUmer | Cloud Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MainComponent>{children}</MainComponent>
      </body>
    </html>
  );
}